### ISSUE TITLE
Voicemeeter module didn't work with new versions of Voicemeeter

### ISSUE THREAD

**Issue by Piripe** [diogotr7/Artemis.Plugins#12]
I'm using a new version of Voicemeeter (3.0.2.6) but the Artemis module no longer work.
Can you update the remote API?

**Comment by diogotr7** [comment]
Hey, do you get any error? Upload logs please. I can't find any indication that the API changed, so it might just be a bug

**Comment by Piripe** [comment]
Here's the logs [Artemis log-20221113.log](https://github.com/diogotr7/Artemis.Plugins/files/9996209/Artemis.log-20221113.log)

**Comment by diogotr7** [comment]
The error doesn't really tell me anything. I've pushed a new version that should have more info in the log. Please try with that and upload a log. (If you are available, diagnosing this on the discord is easier)

**Comment by Piripe** [comment]
"AlreadyLoggedIn" ???
```
2022-11-13 13:30:55.379 [WRN] [Artemis.Core.Services.PluginManagementService] Plugin feature 'Artemis.Plugins.Modules.VoiceMeeter.VoiceMeeterModule - VoiceMeeter v1.0.0.0 - 93e77647-43f5-4e24-8843-9ea8c51dafce' failed to enable.
System.AggregateException: One or more errors occurred. (Error connecting to voicemeeter: AlreadyLoggedIn)
 ---> Artemis.Core.ArtemisPluginException: Error connecting to voicemeeter: AlreadyLoggedIn
   at Artemis.Plugins.Modules.VoiceMeeter.VoiceMeeterModule.Enable() in D:\a\Artemis.Plugins\Artemis.Plugins\src\Artemis.Plugins.Modules.VoiceMeeter\VoiceMeeterModule.cs:line 23
   at Artemis.Core.Modules.Module.InternalEnable() in D:\a\1\s\Artemis\src\Artemis.Core\Plugins\Modules\Module.cs:line 317
   at Artemis.Core.Modules.Module`1.InternalEnable() in D:\a\1\s\Artemis\src\Artemis.Core\Plugins\Modules\Module.cs:line 85
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at Artemis.Core.PluginFeature.SetEnabled(Boolean enable, Boolean isAutoEnable) in D:\a\1\s\Artemis\src\Artemis.Core\Plugins\PluginFeature.cs:line 151
   at Artemis.Core.Services.PluginManagementService.EnablePluginFeature(PluginFeature pluginFeature, Boolean saveState, Boolean isAutoEnable) in D:\a\1\s\Artemis\src\Artemis.Core\Services\PluginManagementService.cs:line 660
```

**Comment by diogotr7** [comment]
Try this build: https://github.com/diogotr7/Artemis.Plugins/actions/runs/3455753602

I've made it so AlreadyLoggedIn is accepted as success. I'm unsure why this changed, but test it please :)

**Comment by Piripe** [comment]
Still not working...

```
2022-11-13 19:09:43.092 [WRN] [Artemis.Core.Services.PluginManagementService] Plugin feature 'Artemis.Plugins.Modules.VoiceMeeter.VoiceMeeterModule - VoiceMeeter v1.0.0.0 - 93e77647-43f5-4e24-8843-9ea8c51dafce' failed to enable during attempt (2/3), scheduling a retry in "00:00:20".
Artemis.Core.ArtemisPluginLockException: Found a lock file, skipping load.
   at Artemis.Core.PluginFeature.SetEnabled(Boolean enable, Boolean isAutoEnable) in D:\a\1\s\Artemis\src\Artemis.Core\Plugins\PluginFeature.cs:line 140
   at Artemis.Core.Services.PluginManagementService.EnablePluginFeature(PluginFeature pluginFeature, Boolean saveState, Boolean isAutoEnable) in D:\a\1\s\Artemis\src\Artemis.Core\Services\PluginManagementService.cs:line 660
```
[[Full logs]](https://github.com/diogotr7/Artemis.Plugins/files/9997932/Artemis.log-20221113.log)

**Comment by diogotr7** [comment]
That error just means it failed last time. Does it crash artemis or something like that? Try enabling it manually in the settings.

**Comment by Piripe** [comment]
It makes Artemis crash half of the time when I start it. And when I enable it (without a crash), I can't see it in the data model.

![image](https://user-images.githubusercontent.com/77517308/201659211-a249fb6e-add5-445c-be46-c981f85da62a.png)

**Comment by diogotr7** [comment]
you shoulds have mentioned the crash.

Look in event viewer if there's any '.NET app crash' or something similar to that. I'm not sure why it would cause a crash. The voicemeeter docs don't mention any changes.

**Comment by Piripe** [comment]
I see these errors

![image](https://user-images.githubusercontent.com/77517308/201682016-52137ff5-3721-44d7-894e-1e53a41adc40.png)
![image](https://user-images.githubusercontent.com/77517308/201681916-f1624e73-e56c-4460-8096-6f03073116be.png)

**Comment by diogotr7** [comment]
Test this please: https://github.com/diogotr7/Artemis.Plugins/actions/runs/3462375433

**Comment by Piripe** [comment]
Nothing changed. I still can't see it in the data model, it's the exact same errors in the event viewer and there is no error in the Artemis logs.

**Comment by diogotr7** [comment]
[Fixed](https://github.com/diogotr7/Artemis.Plugins/commit/1f61efa71bca46611d6196fb129ac911c75907e3)
